### ISSUE TITLE
Can I buy raffle.com?

### ISSUE THREAD

**Issue by ianhd** [austinonrails/rafflr#2]
Thanks!

**Comment by ianhd** [comment]
Autocorrect. Sorry. Meant rafflr.com

**Comment by damon** [comment]
@ianhd it's not really for sale. what do you have in mind?

**Comment by ianhd** [comment]
I'm really hoping to find a permanent home for http://the-raffler.azurewebsites.net 

I built it for my wife who sells children's books. She often does a raffle for prizes to give out to customers.
